version: 1
accounts:
  - name: alice
    coins: ["200000000numi"]
  - name: bob
    coins: ["100000000numi"]
  - name: oliver
    coins: ["100000000numi"]
  - name: olivia
    coins: ["100000000numi"]
validators:
  - name: alice
    bonded: "100000000numi"
client:
  openapi:
    path: "docs/static/openapi.yml"
  typescript:
    path: "ts-client"
  vuex:
    path: "vue/src/store"
faucet:
  name: bob
  coins: ["100000numi"]
genesis:
  app_state:
    crisis:
      constant_fee:
        denom: "numi"
    gov:
      deposit_params:
        min_deposit:
          - amount: "10000000"
            denom: "numi"
    mint:
      params:
        mint_denom: "numi"
    staking:
      params:
        bond_denom: "numi"
    numi:
      params:
        identityVerifiers: numi1uwn82unswe0dfz6fgkvwzdn4exualah3j53mke,numi1f68dytj3lr4p8gjul3zzev7avmcuq4js23d422

