// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: numi/numi/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgCreateAndVerifyUser struct {
	Creator           string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	UserId            string `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
	FirstName         string `protobuf:"bytes,3,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName          string `protobuf:"bytes,4,opt,name=lastName,proto3" json:"lastName,omitempty"`
	CountryCode       string `protobuf:"bytes,5,opt,name=countryCode,proto3" json:"countryCode,omitempty"`
	SubnationalEntity string `protobuf:"bytes,6,opt,name=subnationalEntity,proto3" json:"subnationalEntity,omitempty"`
	City              string `protobuf:"bytes,7,opt,name=city,proto3" json:"city,omitempty"`
	Bio               string `protobuf:"bytes,8,opt,name=bio,proto3" json:"bio,omitempty"`
	Referrer          string `protobuf:"bytes,9,opt,name=referrer,proto3" json:"referrer,omitempty"`
	AccountAddress    string `protobuf:"bytes,10,opt,name=accountAddress,proto3" json:"accountAddress,omitempty"`
}

func (m *MsgCreateAndVerifyUser) Reset()         { *m = MsgCreateAndVerifyUser{} }
func (m *MsgCreateAndVerifyUser) String() string { return proto.CompactTextString(m) }
func (*MsgCreateAndVerifyUser) ProtoMessage()    {}
func (*MsgCreateAndVerifyUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_b554cc2a1a21fbb5, []int{0}
}
func (m *MsgCreateAndVerifyUser) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateAndVerifyUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateAndVerifyUser.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateAndVerifyUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateAndVerifyUser.Merge(m, src)
}
func (m *MsgCreateAndVerifyUser) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateAndVerifyUser) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateAndVerifyUser.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateAndVerifyUser proto.InternalMessageInfo

func (m *MsgCreateAndVerifyUser) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgCreateAndVerifyUser) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *MsgCreateAndVerifyUser) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *MsgCreateAndVerifyUser) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *MsgCreateAndVerifyUser) GetCountryCode() string {
	if m != nil {
		return m.CountryCode
	}
	return ""
}

func (m *MsgCreateAndVerifyUser) GetSubnationalEntity() string {
	if m != nil {
		return m.SubnationalEntity
	}
	return ""
}

func (m *MsgCreateAndVerifyUser) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *MsgCreateAndVerifyUser) GetBio() string {
	if m != nil {
		return m.Bio
	}
	return ""
}

func (m *MsgCreateAndVerifyUser) GetReferrer() string {
	if m != nil {
		return m.Referrer
	}
	return ""
}

func (m *MsgCreateAndVerifyUser) GetAccountAddress() string {
	if m != nil {
		return m.AccountAddress
	}
	return ""
}

type MsgCreateAndVerifyUserResponse struct {
}

func (m *MsgCreateAndVerifyUserResponse) Reset()         { *m = MsgCreateAndVerifyUserResponse{} }
func (m *MsgCreateAndVerifyUserResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCreateAndVerifyUserResponse) ProtoMessage()    {}
func (*MsgCreateAndVerifyUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b554cc2a1a21fbb5, []int{1}
}
func (m *MsgCreateAndVerifyUserResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateAndVerifyUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateAndVerifyUserResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateAndVerifyUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateAndVerifyUserResponse.Merge(m, src)
}
func (m *MsgCreateAndVerifyUserResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateAndVerifyUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateAndVerifyUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateAndVerifyUserResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgCreateAndVerifyUser)(nil), "johnreitano.numi.numi.MsgCreateAndVerifyUser")
	proto.RegisterType((*MsgCreateAndVerifyUserResponse)(nil), "johnreitano.numi.numi.MsgCreateAndVerifyUserResponse")
}

func init() { proto.RegisterFile("numi/numi/tx.proto", fileDescriptor_b554cc2a1a21fbb5) }

var fileDescriptor_b554cc2a1a21fbb5 = []byte{
	// 349 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0xcf, 0x4a, 0x42, 0x41,
	0x14, 0xc6, 0xbd, 0x6a, 0xfe, 0x39, 0x41, 0xd4, 0x44, 0x32, 0x48, 0x5c, 0xc4, 0x45, 0xb8, 0xa8,
	0x2b, 0x14, 0x3d, 0x80, 0x4a, 0x8b, 0x16, 0xb6, 0x10, 0x6a, 0xd1, 0xee, 0xfe, 0x39, 0xea, 0x84,
	0xce, 0xc8, 0x99, 0xb9, 0xe0, 0xa5, 0x5d, 0x4f, 0xd0, 0x13, 0xb5, 0x6e, 0xe9, 0xb2, 0x65, 0xe8,
	0x8b, 0xc4, 0x1d, 0xb5, 0xa4, 0xee, 0xa6, 0xcd, 0x30, 0xdf, 0xf7, 0xfb, 0x18, 0x3e, 0xce, 0x1c,
	0x60, 0x32, 0x9e, 0x8a, 0xb6, 0x3d, 0xcc, 0xdc, 0x9b, 0x91, 0x32, 0x8a, 0x9d, 0x3c, 0xa9, 0xb1,
	0x24, 0x14, 0xc6, 0x97, 0xca, 0x4b, 0x91, 0x3d, 0x9a, 0x6f, 0x79, 0xa8, 0xf5, 0xf5, 0xa8, 0x47,
	0xe8, 0x1b, 0xec, 0xc8, 0xe8, 0x01, 0x49, 0x0c, 0x93, 0x7b, 0x8d, 0xc4, 0x38, 0x94, 0xc3, 0xd4,
	0x56, 0xc4, 0x9d, 0x86, 0xd3, 0xaa, 0x0e, 0xb6, 0x92, 0xd5, 0xa0, 0x14, 0x6b, 0xa4, 0xdb, 0x88,
	0xe7, 0x2d, 0xd8, 0x28, 0x76, 0x0a, 0xd5, 0xa1, 0x20, 0x6d, 0xee, 0xfc, 0x29, 0xf2, 0x82, 0x45,
	0x3f, 0x06, 0xab, 0x43, 0x65, 0xe2, 0x6f, 0x60, 0xd1, 0xc2, 0x6f, 0xcd, 0x1a, 0xb0, 0x1f, 0xaa,
	0x58, 0x1a, 0x4a, 0x7a, 0x2a, 0x42, 0xbe, 0x67, 0xf1, 0xae, 0xc5, 0xce, 0xe1, 0x48, 0xc7, 0x81,
	0xf4, 0x8d, 0x50, 0xd2, 0x9f, 0xdc, 0x48, 0x23, 0x4c, 0xc2, 0x4b, 0x36, 0xf7, 0x17, 0x30, 0x06,
	0xc5, 0x30, 0x0d, 0x94, 0x6d, 0xc0, 0xde, 0xd9, 0x21, 0x14, 0x02, 0xa1, 0x78, 0xc5, 0x5a, 0xe9,
	0x35, 0x6d, 0x44, 0x38, 0x44, 0x22, 0x24, 0x5e, 0x5d, 0x37, 0xda, 0x6a, 0x76, 0x06, 0x07, 0x7e,
	0x68, 0x0b, 0x74, 0xa2, 0x88, 0x50, 0x6b, 0x0e, 0x36, 0xf1, 0xcb, 0x6d, 0x36, 0xc0, 0xcd, 0x9e,
	0xdf, 0x00, 0xf5, 0x4c, 0x49, 0x8d, 0x97, 0x2f, 0x0e, 0x14, 0xfa, 0x7a, 0xc4, 0x9e, 0xe1, 0x38,
	0x6b, 0xcc, 0x17, 0x5e, 0xe6, 0xcf, 0x78, 0xd9, 0xaf, 0xd6, 0xaf, 0xff, 0x15, 0xdf, 0x96, 0xe8,
	0x76, 0xdf, 0x97, 0xae, 0xb3, 0x58, 0xba, 0xce, 0xe7, 0xd2, 0x75, 0x5e, 0x57, 0x6e, 0x6e, 0xb1,
	0x72, 0x73, 0x1f, 0x2b, 0x37, 0xf7, 0xd8, 0x1a, 0x09, 0x33, 0x8e, 0x03, 0x2f, 0x54, 0xd3, 0xf6,
	0xce, 0xd3, 0xeb, 0xf5, 0x99, 0x6f, 0xb6, 0x28, 0x99, 0xa1, 0x0e, 0x4a, 0x76, 0x93, 0xae, 0xbe,
	0x02, 0x00, 0x00, 0xff, 0xff, 0xe1, 0x08, 0x63, 0xcc, 0x5f, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	CreateAndVerifyUser(ctx context.Context, in *MsgCreateAndVerifyUser, opts ...grpc.CallOption) (*MsgCreateAndVerifyUserResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) CreateAndVerifyUser(ctx context.Context, in *MsgCreateAndVerifyUser, opts ...grpc.CallOption) (*MsgCreateAndVerifyUserResponse, error) {
	out := new(MsgCreateAndVerifyUserResponse)
	err := c.cc.Invoke(ctx, "/johnreitano.numi.numi.Msg/CreateAndVerifyUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	CreateAndVerifyUser(context.Context, *MsgCreateAndVerifyUser) (*MsgCreateAndVerifyUserResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) CreateAndVerifyUser(ctx context.Context, req *MsgCreateAndVerifyUser) (*MsgCreateAndVerifyUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAndVerifyUser not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_CreateAndVerifyUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreateAndVerifyUser)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CreateAndVerifyUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/johnreitano.numi.numi.Msg/CreateAndVerifyUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CreateAndVerifyUser(ctx, req.(*MsgCreateAndVerifyUser))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "johnreitano.numi.numi.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAndVerifyUser",
			Handler:    _Msg_CreateAndVerifyUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "numi/numi/tx.proto",
}

func (m *MsgCreateAndVerifyUser) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateAndVerifyUser) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateAndVerifyUser) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.AccountAddress) > 0 {
		i -= len(m.AccountAddress)
		copy(dAtA[i:], m.AccountAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.AccountAddress)))
		i--
		dAtA[i] = 0x52
	}
	if len(m.Referrer) > 0 {
		i -= len(m.Referrer)
		copy(dAtA[i:], m.Referrer)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Referrer)))
		i--
		dAtA[i] = 0x4a
	}
	if len(m.Bio) > 0 {
		i -= len(m.Bio)
		copy(dAtA[i:], m.Bio)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Bio)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.City) > 0 {
		i -= len(m.City)
		copy(dAtA[i:], m.City)
		i = encodeVarintTx(dAtA, i, uint64(len(m.City)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.SubnationalEntity) > 0 {
		i -= len(m.SubnationalEntity)
		copy(dAtA[i:], m.SubnationalEntity)
		i = encodeVarintTx(dAtA, i, uint64(len(m.SubnationalEntity)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.CountryCode) > 0 {
		i -= len(m.CountryCode)
		copy(dAtA[i:], m.CountryCode)
		i = encodeVarintTx(dAtA, i, uint64(len(m.CountryCode)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.LastName) > 0 {
		i -= len(m.LastName)
		copy(dAtA[i:], m.LastName)
		i = encodeVarintTx(dAtA, i, uint64(len(m.LastName)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.FirstName) > 0 {
		i -= len(m.FirstName)
		copy(dAtA[i:], m.FirstName)
		i = encodeVarintTx(dAtA, i, uint64(len(m.FirstName)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.UserId) > 0 {
		i -= len(m.UserId)
		copy(dAtA[i:], m.UserId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.UserId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgCreateAndVerifyUserResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateAndVerifyUserResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateAndVerifyUserResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgCreateAndVerifyUser) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.UserId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.FirstName)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.LastName)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.CountryCode)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.SubnationalEntity)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.City)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Bio)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Referrer)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.AccountAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgCreateAndVerifyUserResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgCreateAndVerifyUser) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateAndVerifyUser: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateAndVerifyUser: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UserId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UserId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FirstName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FirstName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LastName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CountryCode", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CountryCode = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SubnationalEntity", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SubnationalEntity = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field City", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.City = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Bio", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Bio = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Referrer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Referrer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AccountAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AccountAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreateAndVerifyUserResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateAndVerifyUserResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateAndVerifyUserResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
